
//Set path to SmartSlog KP Library
#include <generic.h>

#ifndef _GENERATED_ONTOLOGY
#define	_GENERATED_ONTOLOGY


#ifdef	__cplusplus
extern "C" {
#endif


#define INCLUDE_ALL_ONT_ENTITIES 1
#ifdef INCLUDE_ALL_ONT_ENTITIES

#define INCLUDE_PROPERTY_MBOX 1
#define INCLUDE_PROPERTY_PRESENTATIONURL 1
#define INCLUDE_PROPERTY_CONTENTURL 1
#define INCLUDE_PROPERTY_ORGANIZATION 1
#define INCLUDE_PROPERTY_SECTIONSTARTTIME 1
#define INCLUDE_PROPERTY_ENDPRESENTATION 1
#define INCLUDE_PROPERTY_CURRENTSLIDENUM 1
#define INCLUDE_PROPERTY_HOLDSACTIVITY 1
#define INCLUDE_PROPERTY_ACTIVITYTITLE 1
#define INCLUDE_PROPERTY_USERNAME 1
#define INCLUDE_PROPERTY_TIMESLOTACTUALDURATION 1
#define INCLUDE_PROPERTY_TOPIC_INTEREST 1
#define INCLUDE_PROPERTY_PASSWORD 1
#define INCLUDE_PROPERTY_TIMESLOTTITLE 1
#define INCLUDE_PROPERTY_PHONE 1
#define INCLUDE_PROPERTY_STARTCONFERENCE 1
#define INCLUDE_PROPERTY_CURRENTSLIDECOUNT 1
#define INCLUDE_PROPERTY_HASSERVICE 1
#define INCLUDE_PROPERTY_SECTIONTITLE 1
#define INCLUDE_PROPERTY_SRPASSWORD 1
#define INCLUDE_PROPERTY_PERSONINFORMATION 1
#define INCLUDE_PROPERTY_CURRENTSLIDEIMG 1
#define INCLUDE_PROPERTY_NEXTTIMESLOT 1
#define INCLUDE_PROPERTY_TIMESLOTSPEAKERNAME 1
#define INCLUDE_PROPERTY_SRLOGIN 1
#define INCLUDE_PROPERTY_PRESENTATIONTITLE 1
#define INCLUDE_PROPERTY_THEMEID 1
#define INCLUDE_PROPERTY_HASSECTION 1
#define INCLUDE_PROPERTY_FIRSTTIMESLOT 1
#define INCLUDE_PROPERTY_SERVICENAME 1
#define INCLUDE_PROPERTY_NAME 1
#define INCLUDE_PROPERTY_PRESENTATIONTAGS 1
#define INCLUDE_PROPERTY_STARTPRESENTATION 1
#define INCLUDE_PROPERTY_CURRENTTIMESLOT 1
#define INCLUDE_PROPERTY_SHOWSLIDE 1
#define INCLUDE_PROPERTY_UPDATEPRESENTATION 1
#define INCLUDE_PROPERTY_ENDCONFERENCE 1
#define INCLUDE_PROPERTY_SERVICEDESCRIPTION 1
#define INCLUDE_PROPERTY_TIMESLOTPERSON 1
#define INCLUDE_PROPERTY_THEMESTATUS 1
#define INCLUDE_PROPERTY_STATUS 1
#define INCLUDE_PROPERTY_TIMESLOTPRESENTATION 1
#define INCLUDE_PROPERTY_WLANMAC 1
#define INCLUDE_PROPERTY_ACCOUNT 1
#define INCLUDE_PROPERTY_TIMESLOTDURATION 1
#define INCLUDE_PROPERTY_SECTIONDATE 1
#define INCLUDE_PROPERTY_AGE 1
#define INCLUDE_PROPERTY_UPDATEAGENDA 1
#define INCLUDE_PROPERTY_IMG 1
#define INCLUDE_PROPERTY_LANGUAGE 1
#define INCLUDE_PROPERTY_HASPRESENTATION 1
#define INCLUDE_PROPERTY_CURRENTPRESENTATION 1
#define INCLUDE_PROPERTY_HASCONTEXT 1
#define INCLUDE_PROPERTY_STARTCONFERENCEFROM 1
#define INCLUDE_PROPERTY_SERVICESTATUS 1
#define INCLUDE_PROPERTY_CURRENTSECTION 1
#define INCLUDE_CLASS_TIMESLOT 1
#define INCLUDE_CLASS_PROFILE 1
#define INCLUDE_CLASS_CONFERENCESERVICE 1
#define INCLUDE_CLASS_CONTENTSERVICE 1
#define INCLUDE_CLASS_NOTHING 1
#define INCLUDE_CLASS_PRESENTATION 1
#define INCLUDE_CLASS_SMARTROOM 1
#define INCLUDE_CLASS_BLOG 1
#define INCLUDE_CLASS_PERSON 1
#define INCLUDE_CLASS_ACTIVITY 1
#define INCLUDE_CLASS_AGENDANOTIFICATION 1
#define INCLUDE_CLASS_PRESENTATIONNOTIFICATION 1
#define INCLUDE_CLASS_THING 1
#define INCLUDE_CLASS_CONTEXT 1
#define INCLUDE_CLASS_CLIENTNOTIFICATION 1
#define INCLUDE_CLASS_PRESENTATIONSERVICE 1
#define INCLUDE_CLASS_ONLINEACCOUNT 1
#define INCLUDE_CLASS_SECTION 1
#define INCLUDE_CLASS_CONFERENCENOTIFICATION 1
#define INCLUDE_CLASS_SERVICE 1
#define INCLUDE_CLASS_THEME 1


#else

#define INCLUDE_PROPERTY_MBOX 0
#define INCLUDE_PROPERTY_PRESENTATIONURL 0
#define INCLUDE_PROPERTY_CONTENTURL 0
#define INCLUDE_PROPERTY_ORGANIZATION 0
#define INCLUDE_PROPERTY_SECTIONSTARTTIME 0
#define INCLUDE_PROPERTY_ENDPRESENTATION 0
#define INCLUDE_PROPERTY_CURRENTSLIDENUM 0
#define INCLUDE_PROPERTY_HOLDSACTIVITY 0
#define INCLUDE_PROPERTY_ACTIVITYTITLE 0
#define INCLUDE_PROPERTY_USERNAME 0
#define INCLUDE_PROPERTY_TIMESLOTACTUALDURATION 0
#define INCLUDE_PROPERTY_TOPIC_INTEREST 0
#define INCLUDE_PROPERTY_PASSWORD 0
#define INCLUDE_PROPERTY_TIMESLOTTITLE 0
#define INCLUDE_PROPERTY_PHONE 0
#define INCLUDE_PROPERTY_STARTCONFERENCE 0
#define INCLUDE_PROPERTY_CURRENTSLIDECOUNT 0
#define INCLUDE_PROPERTY_HASSERVICE 0
#define INCLUDE_PROPERTY_SECTIONTITLE 0
#define INCLUDE_PROPERTY_SRPASSWORD 0
#define INCLUDE_PROPERTY_PERSONINFORMATION 0
#define INCLUDE_PROPERTY_CURRENTSLIDEIMG 0
#define INCLUDE_PROPERTY_NEXTTIMESLOT 0
#define INCLUDE_PROPERTY_TIMESLOTSPEAKERNAME 0
#define INCLUDE_PROPERTY_SRLOGIN 0
#define INCLUDE_PROPERTY_PRESENTATIONTITLE 0
#define INCLUDE_PROPERTY_THEMEID 0
#define INCLUDE_PROPERTY_HASSECTION 0
#define INCLUDE_PROPERTY_FIRSTTIMESLOT 0
#define INCLUDE_PROPERTY_SERVICENAME 0
#define INCLUDE_PROPERTY_NAME 0
#define INCLUDE_PROPERTY_PRESENTATIONTAGS 0
#define INCLUDE_PROPERTY_STARTPRESENTATION 0
#define INCLUDE_PROPERTY_CURRENTTIMESLOT 0
#define INCLUDE_PROPERTY_SHOWSLIDE 0
#define INCLUDE_PROPERTY_UPDATEPRESENTATION 0
#define INCLUDE_PROPERTY_ENDCONFERENCE 0
#define INCLUDE_PROPERTY_SERVICEDESCRIPTION 0
#define INCLUDE_PROPERTY_TIMESLOTPERSON 0
#define INCLUDE_PROPERTY_THEMESTATUS 0
#define INCLUDE_PROPERTY_STATUS 0
#define INCLUDE_PROPERTY_TIMESLOTPRESENTATION 0
#define INCLUDE_PROPERTY_WLANMAC 0
#define INCLUDE_PROPERTY_ACCOUNT 0
#define INCLUDE_PROPERTY_TIMESLOTDURATION 0
#define INCLUDE_PROPERTY_SECTIONDATE 0
#define INCLUDE_PROPERTY_AGE 0
#define INCLUDE_PROPERTY_UPDATEAGENDA 0
#define INCLUDE_PROPERTY_IMG 0
#define INCLUDE_PROPERTY_LANGUAGE 0
#define INCLUDE_PROPERTY_HASPRESENTATION 0
#define INCLUDE_PROPERTY_CURRENTPRESENTATION 0
#define INCLUDE_PROPERTY_HASCONTEXT 0
#define INCLUDE_PROPERTY_STARTCONFERENCEFROM 0
#define INCLUDE_PROPERTY_SERVICESTATUS 0
#define INCLUDE_PROPERTY_CURRENTSECTION 0
#define INCLUDE_CLASS_TIMESLOT 0
#define INCLUDE_CLASS_PROFILE 0
#define INCLUDE_CLASS_CONFERENCESERVICE 0
#define INCLUDE_CLASS_CONTENTSERVICE 0
#define INCLUDE_CLASS_NOTHING 0
#define INCLUDE_CLASS_PRESENTATION 0
#define INCLUDE_CLASS_SMARTROOM 0
#define INCLUDE_CLASS_BLOG 0
#define INCLUDE_CLASS_PERSON 0
#define INCLUDE_CLASS_ACTIVITY 0
#define INCLUDE_CLASS_AGENDANOTIFICATION 0
#define INCLUDE_CLASS_PRESENTATIONNOTIFICATION 0
#define INCLUDE_CLASS_THING 0
#define INCLUDE_CLASS_CONTEXT 0
#define INCLUDE_CLASS_CLIENTNOTIFICATION 0
#define INCLUDE_CLASS_PRESENTATIONSERVICE 0
#define INCLUDE_CLASS_ONLINEACCOUNT 0
#define INCLUDE_CLASS_SECTION 0
#define INCLUDE_CLASS_CONFERENCENOTIFICATION 0
#define INCLUDE_CLASS_SERVICE 0
#define INCLUDE_CLASS_THEME 0


#endif


#if INCLUDE_CLASS_TIMESLOT
extern class_t *CLASS_TIMESLOT;
#endif
#if INCLUDE_CLASS_PROFILE
extern class_t *CLASS_PROFILE;
#endif
#if INCLUDE_CLASS_CONFERENCESERVICE
extern class_t *CLASS_CONFERENCESERVICE;
#endif
#if INCLUDE_CLASS_CONTENTSERVICE
extern class_t *CLASS_CONTENTSERVICE;
#endif
#if INCLUDE_CLASS_NOTHING
extern class_t *CLASS_NOTHING;
#endif
#if INCLUDE_CLASS_PRESENTATION
extern class_t *CLASS_PRESENTATION;
#endif
#if INCLUDE_CLASS_SMARTROOM
extern class_t *CLASS_SMARTROOM;
#endif
#if INCLUDE_CLASS_BLOG
extern class_t *CLASS_BLOG;
#endif
#if INCLUDE_CLASS_PERSON
extern class_t *CLASS_PERSON;
#endif
#if INCLUDE_CLASS_ACTIVITY
extern class_t *CLASS_ACTIVITY;
#endif
#if INCLUDE_CLASS_AGENDANOTIFICATION
extern class_t *CLASS_AGENDANOTIFICATION;
#endif
#if INCLUDE_CLASS_PRESENTATIONNOTIFICATION
extern class_t *CLASS_PRESENTATIONNOTIFICATION;
#endif
#if INCLUDE_CLASS_THING
extern class_t *CLASS_THING;
#endif
#if INCLUDE_CLASS_CONTEXT
extern class_t *CLASS_CONTEXT;
#endif
#if INCLUDE_CLASS_CLIENTNOTIFICATION
extern class_t *CLASS_CLIENTNOTIFICATION;
#endif
#if INCLUDE_CLASS_PRESENTATIONSERVICE
extern class_t *CLASS_PRESENTATIONSERVICE;
#endif
#if INCLUDE_CLASS_ONLINEACCOUNT
extern class_t *CLASS_ONLINEACCOUNT;
#endif
#if INCLUDE_CLASS_SECTION
extern class_t *CLASS_SECTION;
#endif
#if INCLUDE_CLASS_CONFERENCENOTIFICATION
extern class_t *CLASS_CONFERENCENOTIFICATION;
#endif
#if INCLUDE_CLASS_SERVICE
extern class_t *CLASS_SERVICE;
#endif
#if INCLUDE_CLASS_THEME
extern class_t *CLASS_THEME;
#endif


#if INCLUDE_PROPERTY_MBOX
extern property_t *PROPERTY_MBOX;
#endif
#if INCLUDE_PROPERTY_PRESENTATIONURL
extern property_t *PROPERTY_PRESENTATIONURL;
#endif
#if INCLUDE_PROPERTY_CONTENTURL
extern property_t *PROPERTY_CONTENTURL;
#endif
#if INCLUDE_PROPERTY_ORGANIZATION
extern property_t *PROPERTY_ORGANIZATION;
#endif
#if INCLUDE_PROPERTY_SECTIONSTARTTIME
extern property_t *PROPERTY_SECTIONSTARTTIME;
#endif
#if INCLUDE_PROPERTY_ENDPRESENTATION
extern property_t *PROPERTY_ENDPRESENTATION;
#endif
#if INCLUDE_PROPERTY_CURRENTSLIDENUM
extern property_t *PROPERTY_CURRENTSLIDENUM;
#endif
#if INCLUDE_PROPERTY_HOLDSACTIVITY
extern property_t *PROPERTY_HOLDSACTIVITY;
#endif
#if INCLUDE_PROPERTY_ACTIVITYTITLE
extern property_t *PROPERTY_ACTIVITYTITLE;
#endif
#if INCLUDE_PROPERTY_USERNAME
extern property_t *PROPERTY_USERNAME;
#endif
#if INCLUDE_PROPERTY_TIMESLOTACTUALDURATION
extern property_t *PROPERTY_TIMESLOTACTUALDURATION;
#endif
#if INCLUDE_PROPERTY_TOPIC_INTEREST
extern property_t *PROPERTY_TOPIC_INTEREST;
#endif
#if INCLUDE_PROPERTY_PASSWORD
extern property_t *PROPERTY_PASSWORD;
#endif
#if INCLUDE_PROPERTY_TIMESLOTTITLE
extern property_t *PROPERTY_TIMESLOTTITLE;
#endif
#if INCLUDE_PROPERTY_PHONE
extern property_t *PROPERTY_PHONE;
#endif
#if INCLUDE_PROPERTY_STARTCONFERENCE
extern property_t *PROPERTY_STARTCONFERENCE;
#endif
#if INCLUDE_PROPERTY_CURRENTSLIDECOUNT
extern property_t *PROPERTY_CURRENTSLIDECOUNT;
#endif
#if INCLUDE_PROPERTY_HASSERVICE
extern property_t *PROPERTY_HASSERVICE;
#endif
#if INCLUDE_PROPERTY_SECTIONTITLE
extern property_t *PROPERTY_SECTIONTITLE;
#endif
#if INCLUDE_PROPERTY_SRPASSWORD
extern property_t *PROPERTY_SRPASSWORD;
#endif
#if INCLUDE_PROPERTY_PERSONINFORMATION
extern property_t *PROPERTY_PERSONINFORMATION;
#endif
#if INCLUDE_PROPERTY_CURRENTSLIDEIMG
extern property_t *PROPERTY_CURRENTSLIDEIMG;
#endif
#if INCLUDE_PROPERTY_NEXTTIMESLOT
extern property_t *PROPERTY_NEXTTIMESLOT;
#endif
#if INCLUDE_PROPERTY_TIMESLOTSPEAKERNAME
extern property_t *PROPERTY_TIMESLOTSPEAKERNAME;
#endif
#if INCLUDE_PROPERTY_SRLOGIN
extern property_t *PROPERTY_SRLOGIN;
#endif
#if INCLUDE_PROPERTY_PRESENTATIONTITLE
extern property_t *PROPERTY_PRESENTATIONTITLE;
#endif
#if INCLUDE_PROPERTY_THEMEID
extern property_t *PROPERTY_THEMEID;
#endif
#if INCLUDE_PROPERTY_HASSECTION
extern property_t *PROPERTY_HASSECTION;
#endif
#if INCLUDE_PROPERTY_FIRSTTIMESLOT
extern property_t *PROPERTY_FIRSTTIMESLOT;
#endif
#if INCLUDE_PROPERTY_SERVICENAME
extern property_t *PROPERTY_SERVICENAME;
#endif
#if INCLUDE_PROPERTY_NAME
extern property_t *PROPERTY_NAME;
#endif
#if INCLUDE_PROPERTY_PRESENTATIONTAGS
extern property_t *PROPERTY_PRESENTATIONTAGS;
#endif
#if INCLUDE_PROPERTY_STARTPRESENTATION
extern property_t *PROPERTY_STARTPRESENTATION;
#endif
#if INCLUDE_PROPERTY_CURRENTTIMESLOT
extern property_t *PROPERTY_CURRENTTIMESLOT;
#endif
#if INCLUDE_PROPERTY_SHOWSLIDE
extern property_t *PROPERTY_SHOWSLIDE;
#endif
#if INCLUDE_PROPERTY_UPDATEPRESENTATION
extern property_t *PROPERTY_UPDATEPRESENTATION;
#endif
#if INCLUDE_PROPERTY_ENDCONFERENCE
extern property_t *PROPERTY_ENDCONFERENCE;
#endif
#if INCLUDE_PROPERTY_SERVICEDESCRIPTION
extern property_t *PROPERTY_SERVICEDESCRIPTION;
#endif
#if INCLUDE_PROPERTY_TIMESLOTPERSON
extern property_t *PROPERTY_TIMESLOTPERSON;
#endif
#if INCLUDE_PROPERTY_THEMESTATUS
extern property_t *PROPERTY_THEMESTATUS;
#endif
#if INCLUDE_PROPERTY_STATUS
extern property_t *PROPERTY_STATUS;
#endif
#if INCLUDE_PROPERTY_TIMESLOTPRESENTATION
extern property_t *PROPERTY_TIMESLOTPRESENTATION;
#endif
#if INCLUDE_PROPERTY_WLANMAC
extern property_t *PROPERTY_WLANMAC;
#endif
#if INCLUDE_PROPERTY_ACCOUNT
extern property_t *PROPERTY_ACCOUNT;
#endif
#if INCLUDE_PROPERTY_TIMESLOTDURATION
extern property_t *PROPERTY_TIMESLOTDURATION;
#endif
#if INCLUDE_PROPERTY_SECTIONDATE
extern property_t *PROPERTY_SECTIONDATE;
#endif
#if INCLUDE_PROPERTY_AGE
extern property_t *PROPERTY_AGE;
#endif
#if INCLUDE_PROPERTY_UPDATEAGENDA
extern property_t *PROPERTY_UPDATEAGENDA;
#endif
#if INCLUDE_PROPERTY_IMG
extern property_t *PROPERTY_IMG;
#endif
#if INCLUDE_PROPERTY_LANGUAGE
extern property_t *PROPERTY_LANGUAGE;
#endif
#if INCLUDE_PROPERTY_HASPRESENTATION
extern property_t *PROPERTY_HASPRESENTATION;
#endif
#if INCLUDE_PROPERTY_CURRENTPRESENTATION
extern property_t *PROPERTY_CURRENTPRESENTATION;
#endif
#if INCLUDE_PROPERTY_HASCONTEXT
extern property_t *PROPERTY_HASCONTEXT;
#endif
#if INCLUDE_PROPERTY_STARTCONFERENCEFROM
extern property_t *PROPERTY_STARTCONFERENCEFROM;
#endif
#if INCLUDE_PROPERTY_SERVICESTATUS
extern property_t *PROPERTY_SERVICESTATUS;
#endif
#if INCLUDE_PROPERTY_CURRENTSECTION
extern property_t *PROPERTY_CURRENTSECTION;
#endif



void register_ontology();

	
#ifdef	__cplusplus
}
#endif

#endif /* _GENERATED_ONTOLOGY */
