/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CameraClient */

#ifndef _Included_CameraClient
#define _Included_CameraClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CameraService
 * Method:    connectSmartSpace
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_petrsu_smartroom_android_cameraclient_KP_connectSmartSpace
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     CameraService
 * Method:    publishData
 * Signature: ()I
 */
JNIEXPORT jobjectArray JNICALL Java_petrsu_smartroom_android_cameraclient_KP_getCameraData
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
