
//Set path to SmartSlog KP Library
#include <generic.h>

#ifndef _GENERATED_ONTOLOGY
#define	_GENERATED_ONTOLOGY


#ifdef	__cplusplus
extern "C" {
#endif


#define INCLUDE_ALL_ONT_ENTITIES 1
#ifdef INCLUDE_ALL_ONT_ENTITIES

#define INCLUDE_PROPERTY_CAMERALOGIN 1
#define INCLUDE_PROPERTY_CAMERANAME 1
#define INCLUDE_PROPERTY_SERVERURI 1
#define INCLUDE_PROPERTY_CAMERAPASS 1
#define INCLUDE_PROPERTY_CAMERAIP 1
#define INCLUDE_PROPERTY_CAMERAPORT 1
#define INCLUDE_PROPERTY_CAMERAAPI 1
#define INCLUDE_CLASS_CAMERA 1
#define INCLUDE_CLASS_NOTHING 1
#define INCLUDE_CLASS_THING 1


#else

#define INCLUDE_PROPERTY_CAMERALOGIN 0
#define INCLUDE_PROPERTY_CAMERANAME 0
#define INCLUDE_PROPERTY_SERVERURI 0
#define INCLUDE_PROPERTY_CAMERAPASS 0
#define INCLUDE_PROPERTY_CAMERAIP 0
#define INCLUDE_PROPERTY_CAMERAPORT 0
#define INCLUDE_PROPERTY_CAMERAAPI 0
#define INCLUDE_CLASS_CAMERA 0
#define INCLUDE_CLASS_NOTHING 0
#define INCLUDE_CLASS_THING 0


#endif


#if INCLUDE_CLASS_CAMERA
extern class_t *CLASS_CAMERA;
#endif
#if INCLUDE_CLASS_NOTHING
extern class_t *CLASS_NOTHING;
#endif
#if INCLUDE_CLASS_THING
extern class_t *CLASS_THING;
#endif


#if INCLUDE_PROPERTY_CAMERALOGIN
extern property_t *PROPERTY_CAMERALOGIN;
#endif
#if INCLUDE_PROPERTY_CAMERANAME
extern property_t *PROPERTY_CAMERANAME;
#endif
#if INCLUDE_PROPERTY_SERVERURI
extern property_t *PROPERTY_SERVERURI;
#endif
#if INCLUDE_PROPERTY_CAMERAPASS
extern property_t *PROPERTY_CAMERAPASS;
#endif
#if INCLUDE_PROPERTY_CAMERAIP
extern property_t *PROPERTY_CAMERAIP;
#endif
#if INCLUDE_PROPERTY_CAMERAPORT
extern property_t *PROPERTY_CAMERAPORT;
#endif
#if INCLUDE_PROPERTY_CAMERAAPI
extern property_t *PROPERTY_CAMERAAPI;
#endif



void register_ontology();

	
#ifdef	__cplusplus
}
#endif

#endif /* _GENERATED_ONTOLOGY */
