/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BlogService */

#ifndef _Included_BlogService
#define _Included_BlogService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BlogService
 * Method:    connectSmartSpace
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_BlogService_connectSmartSpace
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     BlogService
 * Method:    publishData
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_BlogService_publishStartData
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     BlogService
 * Method:    publishData
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_BlogService_publishData
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     BlogService
 * Method:    publishData
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT void JNICALL Java_BlogService_deletePublishedData
  (JNIEnv *, jclass);

/*
 * Class:     BlogService
 * Method:    loadTimeslotList
 * Signature: (Lpetrsu/smartroom/android/srclient/Agenda;)I
 */
JNIEXPORT jint JNICALL Java_BlogService_loadTimeslotList
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
