/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class petrsu_smartroom_android_srclient_KP */

#ifndef _Included_petrsu_smartroom_android_srclient_KP
#define _Included_petrsu_smartroom_android_srclient_KP
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     petrsu_smartroom_android_srclient_KP
 * Method:    connectSmartSpace
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_petrsu_smartroom_android_blogclient_KP_connectSmartSpace
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     petrsu_smartroom_android_srclient_KP
 * Method:    loadTimeslotList
 * Signature: (Lpetrsu/smartroom/android/srclient/Agenda;)I
 */
JNIEXPORT jint JNICALL Java_petrsu_smartroom_android_srclient_KP_loadTimeslotList
  (JNIEnv *, jclass, jobject);

/*
 * Class:     petrsu_smartroom_android_srclient_KP
 * Method:    disconnectSmartSpace
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_petrsu_smartroom_android_blogclient_KP_disconnectSmartSpace
  (JNIEnv *, jclass);

/*
 * Class:     petrsu_smartroom_android_srclient_KP
 * Method:    getServicesInfo
 * Signature: (Lpetrsu/smartroom/android/srclient/ServicesMenu;)I
 */
JNIEXPORT jint JNICALL Java_petrsu_smartroom_android_srclient_KP_getServicesInfo
  (JNIEnv *, jclass, jobject);

/*
 * Class:     petrsu_smartroom_android_srclient_KP
 * Method:    userRegistration
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_petrsu_smartroom_android_blogclient_KP_userRegistration
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     petrsu_smartroom_android_srclient_KP
 * Method:    loadPresentation
 * Signature: (Lpetrsu/smartroom/android/srclient/Projector;)I
 */
JNIEXPORT jint JNICALL Java_petrsu_smartroom_android_srclient_KP_loadPresentation
  (JNIEnv *, jclass, jobject);

/*
 * Class:     petrsu_smartroom_android_srclient_KP
 * Method:    initSubscription
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_petrsu_smartroom_android_srclient_KP_initSubscription
  (JNIEnv *, jclass);

/*
 * Class:     petrsu_smartroom_android_srclient_KP
 * Method:    startConference
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_petrsu_smartroom_android_srclient_KP_startConference
  (JNIEnv *, jclass);

/*
 * Class:     petrsu_smartroom_android_srclient_KP
 * Method:    endConference
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_petrsu_smartroom_android_srclient_KP_endConference
  (JNIEnv *, jclass);

/*
 * Class:     petrsu_smartroom_android_srclient_KP
 * Method:    getProjectorClassObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_petrsu_smartroom_android_srclient_KP_getProjectorClassObject
  (JNIEnv *, jclass);

/*
 * Class:     petrsu_smartroom_android_srclient_KP
 * Method:    showSlide
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_petrsu_smartroom_android_srclient_KP_showSlide
  (JNIEnv *, jclass, jint);

/*
 * Class:     petrsu_smartroom_android_srclient_KP
 * Method:    endPresentation
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_petrsu_smartroom_android_srclient_KP_endPresentation
  (JNIEnv *, jclass);

/*
 * Class:     petrsu_smartroom_android_srclient_KP
 * Method:    getCurrentTimeslotIndex
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_petrsu_smartroom_android_srclient_KP_getCurrentTimeslotIndex
  (JNIEnv *, jclass);

/*
 * Class:     petrsu_smartroom_android_srclient_KP
 * Method:    checkSpeakerState
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_petrsu_smartroom_android_srclient_KP_checkSpeakerState
  (JNIEnv *, jclass);

/*
 * Class:     petrsu_smartroom_android_srclient_KP
 * Method:    getMicServiceIP
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_petrsu_smartroom_android_srclient_KP_getMicServiceIP
  (JNIEnv *, jclass);

/*
 * Class:     petrsu_smartroom_android_srclient_KP
 * Method:    getMicServicePort
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_petrsu_smartroom_android_srclient_KP_getMicServicePort
  (JNIEnv *, jclass);

/*
 * Class:     petrsu_smartroom_android_srclient_KP
 * Method:    getSpeakerName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_petrsu_smartroom_android_srclient_KP_getSpeakerName
  (JNIEnv *, jclass);

/*
 * Class:     petrsu_smartroom_android_srclient_KP
 * Method:    personTimeslotIndex
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_petrsu_smartroom_android_srclient_KP_personTimeslotIndex
  (JNIEnv *, jclass);

/*
 * Class:     petrsu_smartroom_android_srclient_KP
 * Method:    checkConnection
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_petrsu_smartroom_android_srclient_KP_checkConnection
  (JNIEnv *, jclass);

/*
 * Class:     petrsu_smartroom_android_srclient_KP
 * Method:    getPresentationLink
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_petrsu_smartroom_android_srclient_KP_getPresentationLink
  (JNIEnv *, jclass, jint);

/*
 * Class:     petrsu_smartroom_android_srclient_KP
 * Method:    registerGuest
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_petrsu_smartroom_android_blogclient_KP_registerGuest
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     petrsu_smartroom_android_srclient_KP
 * Method:    getPersonUuid
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_petrsu_smartroom_android_srclient_KP_getPersonUuid
  (JNIEnv *, jclass);

/**
* @fn Java_petrsu_smartroom_android_srclient_KP_getThemes(JNIEnv *env, jobject obj)
*
* @brief Gets themes data from SS.
*
* @param env - pointer to JNI environment
* @param obj - Blog class object
*
* @return themes list
*/
JNIEXPORT jint JNICALL Java_petrsu_smartroom_android_blogclient_KP_getThemes(JNIEnv *, jclass, jobject);

/**
* @fn Java_petrsu_smartroom_android_srclient_KP_getLog()
*
* @brief Извлекает из SS общий логин на внешнем блог-сервисе.
*
* @param env - pointer to JNI environment
* @param obj - Blog class object
*
* @return общий логин
*/
JNIEXPORT jstring JNICALL Java_petrsu_smartroom_android_blogclient_KP_getLog(JNIEnv *env, jobject *obj);

/**
* @fn Java_petrsu_smartroom_android_srclient_KP_getPass()
*
* @brief Извлекает из SS общий пароль на внешнем блог-сервисе.
*
* @param env - pointer to JNI environment
* @param obj - Blog class object
*
* @return общий пароль
*/
JNIEXPORT jstring JNICALL Java_petrsu_smartroom_android_blogclient_KP_getPass(JNIEnv *env, jobject *obj);

#ifdef __cplusplus
}
#endif
#endif
